### ISSUE TITLE
memory access error while using search suggestions

### ISSUE THREAD

**Issue by l0drex** [alex1701c/QuickWebShortcuts#2]
I'm using default settings except for search suggestions enabled.

As soon as I type `:`, krunner closes immediately. The terminal is showing `Memory access error (memory dump written)`.

_(Please note that I'm using a different language and translated the error.)_

**Comment by alex1701c** [comment]
I was able to reproduce the issue and now it seems to work.

Can you check if https://github.com/alex1701c/QuickWebShortcuts/tree/memory_access_error_bugfix fixes the issue ?

Edit: What distro are you using ? I didn't had the issue on Kubuntu 19.10 and Kubuntu 18.04 but in the beta version of KDE Neon.

**Comment by l0drex** [comment]
I'm using Manjaro KDE.  It worked once, but now I get this error as a notification when typing _hello_:

`ContentAccessDenied: Error transferring https://duckduckgo.com/lite/?q=hello - server replied: Forbidden `

Edit: Appears only when using the direct links from duckduckgo

**Comment by l0drex** [comment]
That seems to be a bug with duckduckgo lite. If I try to open the URL in the browser, I sometimes get no results, sometimes I get a lot.

**Comment by alex1701c** [comment]
I have the same problem, I even get sometimes internal server error messages.

**Comment by l0drex** [comment]
Same with the html version. Every other version of ddg works.
