### ISSUE TITLE
Unable to search

### ISSUE THREAD

**Issue by QazCetelic** [alex1701c/QuickWebShortcuts#3]
![Screenshot](https://user-images.githubusercontent.com/51381523/94188919-54462500-feaa-11ea-812a-2abd93307205.png)
This is my config:
![image](https://user-images.githubusercontent.com/51381523/94189057-86578700-feaa-11ea-8281-85cea26e65e4.png).

**Comment by alex1701c** [comment]
Thank you for reporting. It appears that it is not displayed, because the "Desktop Search" runner produces a ton of results and is quite aggressive about the priority.

Please check if the latest commit fixes the issue.

**Comment by QazCetelic** [comment]
Nope
![image](https://user-images.githubusercontent.com/51381523/94364377-17a44480-00c9-11eb-85f0-43af596e2ece.png)

**Comment by alex1701c** [comment]
Have you restarted KRunner(just run the install script after pulling the latest changes)

**Comment by QazCetelic** [comment]
It's still the same after 
![image](https://user-images.githubusercontent.com/51381523/94451798-1e0cec00-01af-11eb-8bac-83ba6982a16b.png)

**Comment by alex1701c** [comment]
Can you please try to disable the "Desktop Search" runner if you don't need it? You might have to restart krunner (`krunner --replace`) for the change to be applied.

Also another trigger character might do the trick ;)

**Comment by QazCetelic** [comment]
It works now even after enabling desktop search again! Thanks.
