### ISSUE TITLE
QuickWebShortcuts stops working after reboot

### ISSUE THREAD

**Issue by IlabSentuser** [alex1701c/QuickWebShortcuts#4]
Exactly what the title says. I install it and it works, once i reboot i need to reinstall it to make it work. Is there some debug flag i can enable to debug it and provide a log or something? I really love this but the reinstall part is driving me nuts! Hahahaha.

**Comment by alex1701c** [comment]
Hey, is it possible that you have installed it using the `install-user.sh` script? In that case it is a KRunner or rather systemd issue that the user ENV variables are not properly set.

Please uninstall it first (to avoid having redundant files) and the run the `./install.sh script`.

**Comment by IlabSentuser** [comment]
Thanks for the rapid response, i imagined it could had something to do with user installation and decided to try what you said, i cant reboot now for major reasons but will in about an hour and i will let you know. Should had thought about it before posting but it came afterwards :/ Will let you know as soon as i can reboot. Thanks!

**Comment by IlabSentuser** [comment]
I decided i would do the reboot anyway, is rude to keep people waiting, especially people that tries to help xD So i rebooted and yes, it seems to work correctly. Sorry for the dumb issue. Have a nice day!
