### ISSUE TITLE
Fails to install, kcmutils.h not found

### ISSUE THREAD

**Issue by smcbride-ca** [alex1701c/QuickWebShortcuts#6]
`quick_web_shortcuts_config.cpp:9:10: fatal error: kcmutils_version.h: No such file or directory`
When I try to install I get this error. 

pacman -Q kcmutils returns
`kcmutils 5.94.0-1`

Not much more to say

**Comment by alex1701c** [comment]
That seems to be a fallout from the KDE Frameworks header layout changes. I will push a fix today.

**Comment by alex1701c** [comment]
The fix is pushed, released and the KDE Store file is updated. Thanks for reporting this issue :)
